# Generated by Django 4.2.6 on 2024-01-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_assettype_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='fa_icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-camera')", max_length=100),
        ),
    ]
