# Generated by Django 4.2.6 on 2024-01-05 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_reservation_is_recurring_reservation_recurrence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='series_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10, null=True),
        ),
    ]
