# Generated by Django 4.2.6 on 2024-01-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_allowedemaildomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrict_email_domain', models.BooleanField(default=True, verbose_name='Restrict Email Domain')),
            ],
        ),
    ]
