# Generated by Django 4.2.6 on 2024-01-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_appsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSettings',
            new_name='AppSetting',
        ),
    ]
